### ISSUE TITLE
Fails when there are comments in the tsconfig.json or when the tsconfig target is not supported by esbiuld

### ISSUE THREAD

**Issue by remorses** [aelbore/esbuild-jest#10]
You are parsing the tsconfig with `JSON.parse` but it is common to have comments in tsconfig files

You also assume all the tsconfig target values are also valid in esbuild, which is not the case

**Comment by aelbore** [comment]
@remorses thanks for this, please install `esbuild-jest@0.3.0-beta.2` with `esbuild@latest`
I added some options in-case someone needs it.

**Comment by aelbore** [comment]
@remorses thanks for this. if you still encounter issue please create another one.
