### ISSUE TITLE
Jest mocking not working

### ISSUE THREAD

**Issue by lexanth** [aelbore/esbuild-jest#12]
Reproduction: https://github.com/lexanth/esbuild-jest-mock-repro

Mocking in jest doesn't seem to work when using this transformer. I've linked a minimal repo reproducing this - the mock of B should be used for the snapshots, rather than the real B.

I suspect it is related to https://github.com/kulshekhar/ts-jest/issues/90. I've added a second test with the jest.mock manually hoisted (`A.hoisted.test.tsx`), but it still doesn't seem to work (from debugging, it looks like esbuild might still be hoisting the imports above the jest mock call?).

This may turn out to need fixing in esbuild, but in the mean time might be worth a mention in the README as an unusable jest feature.

**Comment by lexanth** [comment]
Just found this, which probably explains it - https://github.com/evanw/esbuild/issues/412

Maybe just a readme change then?

**Comment by RIP21** [comment]
Yeah, adding something into README that will explain how to mock (if it's even possible) modules with how esbuild treats them, will be awesome.

**Comment by aelbore** [comment]
@RIP21 @a-h @lexanth
jest.mock and jest.spy works on `esbuild-jest@0.4.0` just update your `esbuild@latest` 
i tried @evanw example for jest.spy https://github.com/evanw/jest-esbuild-demo
and @lexanth jest.mock bug reproduction work https://github.com/lexanth/esbuild-jest-mock-repro

as per @evanw jest.spy works on cjs format which `esbuild-jest` by default its `cjs` format

let me know if this resolve your issue

**Comment by aelbore** [comment]
my mistakes only spyOn was fixed for this, jest.mock was fixed by @threepointone 
https://github.com/threepointone/esjest-transform

**Comment by aelbore** [comment]
currently working the fix i create a branch 
https://github.com/aelbore/esbuild-jest/tree/jest-mocks-fix

planning to publish this a beta version of 0.5.0-beta.1

**Comment by RIP21** [comment]
So after those fixes esbuild-jest should work as expected? (as with transform)

**Comment by aelbore** [comment]
> So after those fixes esbuild-jest should work as expected? (as with babel transform)

@RIP21 yes it should work as expected, i'm still adding tests to make sure it doesnt affect existing user

**Comment by aelbore** [comment]
@RIP21 please try esbuild-jes@0.5.0-beta.1 for jest.mock i tried @lexanth reproduce repo it works, about sourcemap debug i havent test yet. 👍

**Comment by aelbore** [comment]
@RIP21 @lexanth i will close this issue please install `esbuild-jest@0.5.0` 
Please open new issue if jest.mock with esbuild-jest still not working.
thanks

**Comment by RIP21** [comment]
> @RIP21 @lexanth i will close this issue please install `esbuild-jest@0.5.0`
> Please open new issue if jest.mock with esbuild-jest still not working.
> thanks

Ok. I Will let you know once I'll try it again.

**Comment by a-h** [comment]
Just wanted to say thanks @aelbore - I tested out the changes today in a minimal repo and they worked great!

The example repository is here: https://github.com/a-h/esbuild-mock-test
