### ISSUE TITLE
Not compatible with apple silicon macs

### ISSUE THREAD

**Issue by jarandmi** [aelbore/esbuild-jest#14]
Esbuild introduced support for darwin x86_64 binary (M1 cpu) in version 0.8.17. 
https://github.com/evanw/esbuild/pull/564

I see you are still on version 0.7.8. Any reason not to upgrade?

**Comment by aelbore** [comment]
@jarandmi thanks for this, can you try installing `esbuild-jest@0.3.0` with `esbuild@latest`
let me know if you still encounter errors.

**Comment by aelbore** [comment]
@jarandmi if you install `esbuild-jest@0.3.0` you can install any latest esbuild
i will closed this, if you still encounter issues please submit new issue, again many thanks for using esbuild-jest
