### ISSUE TITLE
Not working with path aliases

### ISSUE THREAD

**Issue by julianklumpers** [aelbore/esbuild-jest#23]
Problem:
When having path aliases in your project. the transformer cannot resolve the file.
 
`Cannot find module '@src/utils/fixtureGenerator/FixtureGenerator'`

referring to this issue: https://github.com/evanw/esbuild/issues/38
It should be fixed by adding a `jsconfig.json` but its not working.

Is there a way to configure this or will this be supported in the near future?

**Comment by julianklumpers** [comment]
Fixed this bu adding this

`
moduleNameMapper: {
   '@src': path.resolve(__dirname, 'src'),
   '@src/*': path.resolve(__dirname, 'src/*'),
}
` 

in jest.config.js.

**Comment by aelbore** [comment]
@julianklumpers thanks for raising this issue, i think i should add the tsconfig options i check on this and let you know.

**Comment by aelbore** [comment]
@julianklumpers for the meantime you do this as workaround in you jest.config.js
```
  moduleNameMapper: {
    "@src/utils/fixtureGenerator/FixtureGenerator": "<rootDir>/your-path-of-genarator-here"
  },
```

**Comment by aelbore** [comment]
@julianklumpers i found this, can you install `alias-hq` and check out there documentation
https://github.com/davestewart/alias-hq/blob/master/docs/integrations.md

let me know if resolve your issue.

**Comment by aelbore** [comment]
@julianklumpers it will not mock the module please see examples
./examples/ts-jsconfig-paths

on this repository

**Comment by aelbore** [comment]
closing on this please create new issue if you still have issues.
