### ISSUE TITLE
feature: preset file

### ISSUE THREAD

**Issue by privatenumber** [aelbore/esbuild-jest#25]
Would be convenient if the default configuration can be set via [preset](https://jestjs.io/docs/configuration#preset-string):

```json5
{
    "preset": "esbuild-jest"
}
```

**Comment by aelbore** [comment]
@privatenumber can you help me what would be the default config? 
thanks

**Comment by privatenumber** [comment]
Seems to me the README describes a default config:
```json5
{
  "transform": {
    "^.+\\.tsx?$": "esbuild-jest"
  }
}
```

----

I found [es-jest](https://github.com/ambar/es-jest) which has the [preset option](https://github.com/ambar/es-jest/blob/main/jest-preset.js). And also without the Babel transform, which was not working for me. Withdrawing my request but feel free to re-open if you'd like.
