### ISSUE TITLE
How to customise the options passed down to esbuild?

### ISSUE THREAD

**Issue by pradel** [aelbore/esbuild-jest#7]
Hi, I would like to pass some options to esbuild. Currently, I can't run the tests on jsx files and I would like to change the parser to jsx / tsx.
Is there a way to do this?

**Comment by aelbore** [comment]
@pradel thanks for asking for this. this is good feature as of now this is no way to configure it, i will try working on this or feel free to contribute

**Comment by aelbore** [comment]
@pradel sorry for the late reply, can you try to install version `esbuild-jest@0.3.0-beta.2` with esbuild@latest
please see readme for some options.

**Comment by pradel** [comment]
That's amazing @aelbore thanks for this 😊 !

**Comment by aelbore** [comment]
@pradel i will closed this
